config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "/products_manager", to: "static_pages#products_manager"
  get "/categories_manager", to: "static_pages#categories_manager"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :products do
    resources :parameters, except: %i(index show)
  end
  devise_for :users
  resources :users
  resources :categories
  resources :comments, only: %i(create destroy)
  resources :ratings, only: %i(create destroy)
  resource :cart, only: [:show]
  resources :order_details, only: %i(create update destroy)
  resources :checkouts, only: %i(index create)
  resources :my_orders, only: [:index]
  resources :orders, only: %i(show update)
  resources :imports, only: %i(index create)
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: %i(products_manager categories_manager)
  before_action :admin_user, only: %i(products_manager categories_manager)

  def home
    @hot_products = Product.hot_trend
    @products = Product.get_lastest_product Settings.product.lastest_product
    @categories = Category.all
  end

  def help; end

  def about; end

  def contact; end

  def categories_manager
    @count = 0
    @categories = Category.all
    @super_categories = Category.get_sub_category 0
  end

  def products_manager
    @products = Product.sort_by_name.paginate(page: params[:page], per_page: Settings.paginate.user_perpage)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1><%= t "about" %></h1>
<p><%= t "hello_world" %></p>

app/views/static_pages/categories_manager.html.erb
<h1><%= t "cate_manager" %></h1>
<div class="row col-md-offset-2">
  <%= render partial: "categories/category_in_manager", collection: @super_categories, as: :category %>
</div>
<div class="row col-md-offset-2 add_btn">
  <button type="button" class="btn btn-primary"><%= link_to t(".add_cate"), new_category_path %></button>
</div>

<div class="row col-md-offset-0">
  <table style="width:100%" class="table_custom">
    <tr class="row_custom header">
      <th class="cell_custom"><%= t ".id" %></th>
      <th class="cell_custom"><%= t ".name" %></th>
      <th class="cell_custom"><%= t ".parent_cate" %></th>
      <th class="cell_custom"><%= t ".actions" %></th>
    </tr>
    <%= render partial: "categories/category_in_table_manager", collection: @categories, as: :category %>
  </table>
</div>

app/views/static_pages/contact.html.erb
<h1><%= t "contact" %></h1>
<p><%= t "hello_world" %></p>

app/views/static_pages/help.html.erb
<h1><%= t "help" %></h1>
<p><%= t "hello_world" %></p>

app/views/static_pages/home.html.erb
<section>
  <div class="container">
    <div class="row">
        <div class="col-sm-3">
          <%= render "layouts/left_sidebar" %>
        </div>
        <div class="col-sm-9 padding-right">
          <div class="features_items"><!--features_items-->
            <h2 class="title text-center"><%= t ".hot_trend" %></h2>
            <% if @hot_products.present? %>
              <%= render @hot_products %>
            <% else %>
              <p style="text-align:center"><%= t "not_found_hot_product" %></p>
            <% end %>
          </div><!--features_items-->
          <div class="features_items"><!--features_items-->
            <h2 class="title text-center"><%= t ".lastest_products" %></h2>
            <% if @products.present? %>
              <%= render @products %>
            <% else %>
              <p><%= t "not_found_product" %></p>
            <% end %>
          </div><!--features_items-->
        </div>
      </div>
  </div>
</section>

app/views/static_pages/products_manager.html.erb
<% provide(:title, t("all_product")) %>
<h1><%= t "all_product" %></h1>

<div class="row col-md-offset-2 add_btn">
  <button type="button" class="btn btn-primary"><%= link_to t("add_product"), new_product_path %></button>
  <%= link_to t("import"), imports_path, class: "btn btn-primary" %>
</div>

<div class="row col-md-offset-0">
  <table style="width:100%" class="table_custom">
    <tr class="row_custom header">
      <th class="cell_custom"><%= t ".id" %></th>
      <th class="cell_custom"><%= t ".image" %></th>
      <th class="cell_custom"><%= t ".name" %></th>
      <th class="cell_custom"><%= t ".price" %></th>
      <th class="cell_custom"><%= t ".quantity" %></th>
      <th class="cell_custom"><%= t ".active" %></th>
      <th class="cell_custom"><%= t ".cate" %></th>
      <th class="cell_custom"><%= t ".action" %></th>
    </tr>
    <%= render partial: "products/product_in_manager", collection: @products, as: :product %>
  </table>
  <%= will_paginate @products %>
</div>