config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "/products_manager", to: "static_pages#products_manager"
  get "/categories_manager", to: "static_pages#categories_manager"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :products do
    resources :parameters, except: %i(index show)
  end
  devise_for :users
  resources :users
  resources :categories
  resources :comments, only: %i(create destroy)
  resources :ratings, only: %i(create destroy)
  resource :cart, only: [:show]
  resources :order_details, only: %i(create update destroy)
  resources :checkouts, only: %i(index create)
  resources :my_orders, only: [:index]
  resources :orders, only: %i(show update)
  resources :imports, only: %i(index create)
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_cart.order_details
  end
end

app/views/carts/_cart_row.html.erb
<div class="row-cart well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= link_to product.name, product %></h4>
      <img class="picture-product" src="<%= product.picture %>">
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right"><%= t".cart_unit" %><span style="color: green">
          <%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit t(".submit"), class: "btn btn-primary update-cart" %>
              <%= link_to t(".delete"), order_item, { data: { confirm: t(".sure") },
               method: :delete, remote: false, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right"><%= t".total_cart" %><span style="color: green">
          <%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if @order_item.present? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.blank? %>
  <p class="text-center">
    <%= image_tag "no-products-found.png" %>
    <br>
    <%= t".cnt1" %> <%= link_to t(".go_back"), root_path %><%= t".cnt2" %>
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render "carts/cart_row", product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<div class="bottom-cart">
  <h2 class="subtotal-cart"><% t ".subtotal" %><%= "#{number_to_currency @cart.subtotal}" %></h2>
  <%= link_to t(".checkout"), checkouts_path, class: "btn btn-primary checkout-button"  %>
</div>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>