config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "/products_manager", to: "static_pages#products_manager"
  get "/categories_manager", to: "static_pages#categories_manager"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :products do
    resources :parameters, except: %i(index show)
  end
  devise_for :users
  resources :users
  resources :categories
  resources :comments, only: %i(create destroy)
  resources :ratings, only: %i(create destroy)
  resource :cart, only: [:show]
  resources :order_details, only: %i(create update destroy)
  resources :checkouts, only: %i(index create)
  resources :my_orders, only: [:index]
  resources :orders, only: %i(show update)
  resources :imports, only: %i(index create)
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true

  before_save{self.parent_id ||= 0}

  scope :get_sub_category, ->(id){where parent_id: id}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_products, only: %i(show)
  before_action :load_cates, except: %i(destroy update)
  before_action :load_cate, except: %i(index create new)
  before_action :avoid_destroy_when_have_sub_category, only: :destroy

  def index; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t ".add_success"
      redirect_to categories_manager_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update_attributes(category_params)
      flash[:success] = t "updated"
      redirect_to categories_manager_path
    else
      render :edit
    end
  end

  def show; end

  def destroy
    if @category.destroy
      flash[:success] = t ".destroy_success"
    else
      flash[:danger] = t ".destroy_fail"
    end
    redirect_to categories_manager_path
  end

  private

  def avoid_destroy_when_have_sub_category
    return unless has_sub_cate? @category
    flash[:danger] = t ".destroy_fail_because_of_sub"
    redirect_to categories_manager_path
  end

  def load_cate
    @category = Category.find_by id: params[:id]
    return if @category
    flash[:danger] = t "cant_find_category"
    redirect_to categories_manager_path
  end

  def load_cates
    @categories = Category.all
  end

  def load_products
    @products = Product.search_by_cate params[:id]
  end

  def category_params
    params.require(:category).permit :name, :parent_id
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def load_product_in_cate category
    @products = category.products
  end

  def display_cate_name_by id
    @cate = Category.find_by(id: id)
    @cate.present? ? @cate.name : id
  end

  def has_sub_cate? category
    @sub_cate = Category.get_sub_category category.id
    @sub_cate.present?
  end
end

app/views/categories/_category.html.erb
<div class="panel-heading">
  <h4 class="panel-title">
    <a data-toggle="collapse" data-parent="#accordian" href="#sportswear">
      <%= link_to category.name, category %>
    </a>
  </h4>
</div>

app/views/categories/_category_detail.html.erb
<div class="category_items">
  <h2 class="title text-center"><%= link_to category.name, category %></h2>
  <% load_product_in_cate category %>
  <%= render @products %>
</div>

app/views/categories/_category_in_manager.html.erb
<%= "---->" * @count %>
<%= link_to category.name, category %><br>
<% @count +=1 %>
<% if has_sub_cate? category %>
  <%= render partial: "categories/category_in_manager",
    collection: Category.get_sub_category(category.id), as: :category %>
<% end %>
<% @count -=1 if @count>0 %>

app/views/categories/_category_in_table_manager.html.erb
<tr class="row_custom">
  <td class="cell_custom"><%= link_to category.id, category %></td>
  <td class="cell_custom"><%= link_to category.name, category %></td>
  <td class="cell_custom"><%= display_cate_name_by(category.parent_id) %></td>
  <td class="cell_custom">
    <% if current_user.admin? %>
      <%= link_to t("delete"), category, method: :delete, data: {confirm: t("confirm_msg")} %> |
      <%= link_to t("update"), edit_category_path(category) %>
    <% end %>
  </td>
</tr>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :parent_id %>
  <%= f.collection_select :parent_id, @categories, :id, :name, {promt: t("choose_cate"), include_blank: t("super_cate")} %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/categories/edit.html.erb
<% provide(:title, t("edit")) %>
<% provide(:button_text, t("update")) %>

<h1><%= t "edit" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/categories/index.html.erb
<section>
  <div class="container">
    <div class="row">
        <div class="col-sm-3">
          <%= render "layouts/left_sidebar" %>
        </div>
        <div class="col-sm-9 padding-right">
          <div class="features_items">
            <%= render partial: "category_detail", collection: @categories, as: :category %>
          </div>
        </div>
      </div>
  </div>
</section>

app/views/categories/new.html.erb
<% provide(:title, t(".add_cate")) %>
<% provide(:button_text, t("create")) %>

<h1><%= t ".add_cate" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/categories/show.html.erb
<section>
  <div class="container">
    <div class="row">
        <div class="col-sm-3">
          <%= render "layouts/left_sidebar" %>
        </div>
        <div class="col-sm-9 padding-right">
          <div class="features_items"><!--features_items-->
            <h2 class="title text-center"><%= t ".product" %></h2>
            <%= render @products %>
          </div><!--features_items-->
        </div>
      </div>
  </div>
</section>