config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "/products_manager", to: "static_pages#products_manager"
  get "/categories_manager", to: "static_pages#categories_manager"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :products do
    resources :parameters, except: %i(index show)
  end
  devise_for :users
  resources :users
  resources :categories
  resources :comments, only: %i(create destroy)
  resources :ratings, only: %i(create destroy)
  resource :cart, only: [:show]
  resources :order_details, only: %i(create update destroy)
  resources :checkouts, only: %i(index create)
  resources :my_orders, only: [:index]
  resources :orders, only: %i(show update)
  resources :imports, only: %i(index create)
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_one :parameter, dependent: :destroy
  has_many :order_details
  has_many :ratings
  has_many :comments

  mount_uploader :picture, PictureUploader

  validates :name, presence: true, length: {maximum: Settings.product.name.maximum_length}
  validates :price, presence: true
  validates :quantity, presence: true,
    numericality: {only_integer: true, greater_than_or_equal_to: Settings.product.than}

  default_scope{where(active: true)}
  scope :sort_by_name, ->{order :name}
  scope :search_by_name, ->(content){where(" name like ?", "%#{content}%")}
  scope :search_by_price, ->(prices){where(price: prices) if prices.present?}
  scope :search_by_cate, ->(category_id){where category_id: category_id}
  scope :hot_trend, ->{joins(:order_details)
    .where("order_details.created_at >= DATE_FORMAT( CURRENT_DATE - INTERVAL 1 MONTH, '%Y/%m/01' )")
    .group("id").order("sum(order_details.quantity) DESC").limit(Settings.product.limit)}
  scope :get_lastest_product, ->(number){order(created_at: :desc).limit(number)}

  private

  def check_if_has_line_item
    if order_details.empty?
      true
    else
      errors.add(:base, Settings.error_destroy_product)
      false
    end
  end

  def self.import file
    spreadsheet = open_spreadsheet file
    if spreadsheet == Settings.unknown_file
      spreadsheet
    else
      header = spreadsheet.row(Settings.product_row)
      (Settings.product_start..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        product = find_or_initialize_by(name: row["name"])
        product.update_attributes(row.to_hash)
      end
    end
  end

  def self.open_spreadsheet file
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path, file_warning: :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, file_warning: :ignore)
    else Settings.unknown_file
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_category, only: %i(index)
  before_action :load_product, except: %i(index create new)
  before_action :load_all_category, only: %i(new edit show)
  before_action :load_rating, only: :show
  before_action :load_comment, only: :show
  before_action :check_if_has_line_item, only: :destroy

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t ".add_success"
      redirect_to products_manager_path
    else
      render :new
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = t "success"
    else
      flash[:danger] = t "destroy_fail"
    end
    redirect_to products_manager_path
  end

  def edit; end

  def update
    if @product.update_attributes(product_params)
      flash[:success] = t "updated"
      redirect_to products_manager_path
    else
      render :edit
    end
  end

  def show
    if @product.ratings.present?
      @avg_score = @product.ratings.average(:score).round(1)
    else
      @avg_score = 0
    end
  end

  def index
    @products = if @category
      @category.products
    else
      Product.search_by_price select_price
    end.search_by_name(params[:search]).sort_by_name
  end

  private

  def check_if_has_line_item
    return if @product.order_details.empty?
    flash[:danger] = t ".destroy_fail"
    redirect_to products_manager_path
  end

  def load_rating
    @rating = current_user.ratings.build if logged_in?
    @ratings = @product.ratings.sort_by_time.paginate(page: params[:page],
      per_page: Settings.paginate.comment_perpage)
  end

  def load_comment
    @comments = @product.comments.sort_by_time.paginate(page: params[:page],
      per_page: Settings.paginate.comment_perpage)
    @comment = current_user.comments.build if logged_in?
  end

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:danger] = t "cant_find_product"
    redirect_to root_url
  end

  def load_category
    unless params[:category].nil?
      @category = Category.find_by name: params[:category]
      return if @category
      render file: "public/404.html"
    end
  end

  def select_price
    if params[:reson].present?
      return if params[:reson][:price] == Settings.controllers.products.all
      start, last = params[:reson][:price].split(Settings.controllers.products.to)
      start..last
    end
  end

  def product_params
    params.require(:product).permit :name, :price, :quantity, :active, :picture, :category_id
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def show_image_for product
    image_tag(product.picture.url, class: "img-responsive")
  end

  def display_availability_for product
    product.active? ? t("in_stock") : t("nolonger_sold")
  end

  def bought_this_product_before?
    if logged_in?
      if (@ordered_list = current_user.orders.ids).present?
        @ordered_list.each do |item|
          @check = current_user.orders.find(item).order_details.find_by product_id: params[:id]
          break if @check.present?
        end
      end
      @check.present?
    else false
    end
  end

  def review_this_product_before?
    if logged_in?
      @check = current_user.ratings.find_by product_id: params[:id]
      @check.present?
    else
      false
    end
  end
end

app/views/products/_average_score.html.erb
<div class="row">
  <div class="col-sm-3">
    <div class="rating-block">
      <span class="glyphicon .glyphicon-star-empty glyphicon-star" id="colorstar"></span>
      <b><%= t "product_avegare" %></b>
      <% if @avg_score > 0 %>
        <div class="bold padding-bottom-7"> <%= @avg_score %> / 5</div>
      <% else %>
        <div class="bold padding-bottom-7"><%= t "no_rating" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_comment_and_review.html.erb
<div class="category-tab shop-details-tab">
  <div class="col-sm-12">
    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#comments" data-toggle="tab">
          <%= t "all_comments" %>
          (<%= show_number_comments_of(@product) %>)
        </a>
      </li>
      <li><a href="#reviews" data-toggle="tab"><%= t "reviews" %></a></li>
    </ul>
  </div>
  <div class="tab-content">

    <div class="tab-pane fade active in" id="comments" >
      <div class="col-sm-12">
        <% if logged_in? %>
          <div class="row">
            <aside class="col-md-12">
              <section class="comment_form">
                <%= render "shared/comment_form" %>
              </section>
            </aside>
          </div>
        <% end %>
        <% if @product.comments.any? %>
          <ol class="comments">
            <%= render @comments %>
          </ol>
          <%= will_paginate @comments %>
        <% end %>
      </div>
    </div>

    <div class="tab-pane fade" id="reviews" >
      <% if bought_this_product_before? && !review_this_product_before? %>
        <div class="col-sm-12">
          <%= render "shared/review_form" %>
        </div>
      <% end %>
      <% if @product.ratings.any? %>
          <ol class="comments">
            <%= render @ratings %>
          </ol>
          <%= will_paginate @ratings %>
        <% end %>
    </div>

  </div>
</div>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :category_id %>
  <%= f.collection_select :category_id, @categories, :id, :name, {promt: t("choose_cate")} %>

  <% if yield(:is_edit?) == "true" %>
    <div class="edit_form_image">
      <%= show_image_for @product %>
    </div>
  <% end %>

  <%= f.label :picture %>
  <%= f.file_field :picture, accept: Settings.picture.accepted_file %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :price %>
  <%= f.number_field :price, class: "form-control" %>

  <%= f.label :quantity %>
  <%= f.number_field :quantity, class: "form-control" %>

  <%= f.label :active %>
  <%= f.check_box :active %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/products/_product.html.erb
<div class="col-sm-4">
  <div class="product-image-wrapper">
    <div class="single-products">
        <div class="productinfo text-center">
          <%= show_image_for product %>
          <h2><%= product.price %></h2>
          <p><%= product.name %></p>
        </div>
        <div class="product-overlay">
          <div class="overlay-content">
            <h2><%= product.price %></h2>
            <p><%= product.name %></p>
            <% if product.quantity != 0 %>
              <%= link_to t(".add-cart"), order_details_path(order_detail: {product_id: product.id, quantity: 1}), remote: true, method: :post, class: "btn btn-default add-to-cart" %>
            <% end %>
          </div>
        </div>
    </div>
    <div class="choose">
      <ul class="nav nav-pills nav-justified">
        <li></i><%= link_to (t".view-detail"), product %></a></li>
      </ul>
    </div>
  </div>
</div>

app/views/products/_product_in_manager.html.erb
<tr class="row_custom">
  <td class="cell_custom"><%= link_to product.id, product %></td>
  <td class="cell_custom"><%= link_to show_image_for(product), product %></td>
  <td class="cell_custom"><%= link_to product.name, product %></td>
  <td class="cell_custom"><%= product.price %></td>
  <td class="cell_custom"><%= product.quantity %></td>
  <td class="cell_custom"><%= product.active %></td>
  <td class="cell_custom"><%= display_cate_name_by product.category_id %></td>
  <td class="cell_custom">
    <% if current_user.admin? %>
      <%= link_to t("update"), edit_product_path(product) %> |
      <% if product.parameter %>
        <%= link_to t("update_para"), edit_product_parameter_path(product, product.parameter.id) %> |
      <% else %>
        <%= link_to t("update_para"), new_product_parameter_path(product) %> |
      <% end %>
      <%= link_to t("delete"), product, method: :delete, data: { confirm: t("confirm_msg") } %>
    <% end %>
  </td>
</tr>

app/views/products/edit.html.erb
<% provide(:title, t("edit")) %>
<% provide(:button_text, t("update")) %>
<% provide(:is_edit?, "true") %>

<h1><%= t "edit" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/products/index.html.erb
<section>
  <div class="container">
    <div class="row">
        <div class="col-sm-3">
          <%= render "layouts/left_sidebar" %>
        </div>
        <div class="col-sm-9 padding-right">
          <div class="features_items"><!--features_items-->
            <h2 class="title text-center"><%= t ".product" %></h2>
            <% if @products.present? %>
              <%= render @products %>
            <% else %>
              <p><%= t "not_found_product" %></p>
            <% end %>
          </div><!--features_items-->
        </div>
      </div>
  </div>
</section>

app/views/products/new.html.erb
<% provide(:title, t(".add_product")) %>
<% provide(:button_text, t(".add_product")) %>

<h1><%= t ".add_product" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/products/show.html.erb
<section>
  <div class="container">
    <div class="row">
        <div class="col-sm-3">
          <%= render "layouts/left_sidebar" %>
        </div>

        <div class="col-sm-9 padding-right">
          <div class="features_items"><!--features_items-->
            <h2 class="title text-center"><%= t ".detail" %></h2>
          </div>
          <div class="col-sm-5">
              <div class="view-product">
                <%= show_image_for @product %>
              </div>
            </div>
            <div class="col-sm-7">
              <div class="product-information"><!--/product-information-->
                <img src="images/product-details/new.jpg" class="newarrival" alt="" />
                <h2><%= @product.name %></h2>
                <h2><%= number_with_delimiter(@product.price, delimiter: " ") %> $</h2>
                <span>
                  <label><%= t ".quantity" %><%= @product.quantity %></label>
                  <%= form_tag "/order_details", remote: true do |f| %>
                    <%= number_field_tag :quantity, 1, class: "form-control number_cart", min: 1 %>
                    <%= hidden_field_tag :product_id, @product.id %>
                    <% if @product.quantity != 0 %>
                      <%= submit_tag t(".add_to_cart"), class: "btn btn-fefault cart" %>
                    <% end %>
                  <% end %>
                  <div class="col-sm-12">
                    <%= render "average_score" %>
                  </div>
                </span>
                <p><b><%= t ".vailability" %></b> <%= display_availability_for @product %></p>
                <br>
                <% if @product.parameter.present? %>
                  <p><b><%= t ".screen" %></b> <%= @product.parameter.screen %></p>
                  <p><b><%= t ".os" %></b> <%= @product.parameter.os %></p>
                  <p><b><%= t ".font_cam" %></b> <%= @product.parameter.camera_front %></p>
                  <p><b><%= t ".back_cam" %></b> <%= @product.parameter.camera_back %></p>
                  <p><b><%= t ".ram" %></b> <%= @product.parameter.ram %></p>
                  <p><b><%= t ".storage" %></b> <%= @product.parameter.memory_storage %></p>
                  <p><b><%= t ".cpu" %></b> <%= @product.parameter.processor %></p>
                <% end %>
              </div><!--/product-information-->
            </div>
          <!--features_items-->
        </div>
        <%= render "comment_and_review" %>
      </div>
  </div>
</section>